In [9]:
from bs4 import BeautifulSoup as bs # pip install beautifulsoup4
from IPython.display import display, IFrame
import requests # pip install requests
import pandas as pd

In [10]:
# Specify the URL of the webpage you want to display
url = "https://indiamapia.com/206451.html"

# Set the width and height of the iframe
width = "100%"
height = "400px"

# Embed the webpage within an iframe and display it
display(IFrame(url, width=width, height=height))

In [22]:
# Specify the URL of the webpage you want to display
url = "https://indiamapia.com/222101.html"

# Set the width and height of the iframe
width = "100%"
height = "400px"

# Embed the webpage within an iframe and display it
display(IFrame(url, width=width, height=height))

In [8]:
type1 = []
type2 = []
type1_pincodes = []
type2_pincodes = []


pincodes = ['121011','124405','124524','127020','127110','131002','131303','131310','133021','134011','134012','134111','134115','141124','143007','143026','143104','143106','143110','144013','144038','144203','144304','144424','147204','151107','160035','160061','160106','173219','174401','174402','174403','175137','176072','176127','176226','177032','177116','181008','181208','181209','184103','184146','201308','202389','202391','202392','202393','202395','202396','202397','202398','202399','202410','202412','202414','202421','202520','202521','202522','202525','202526','202527','205135','205141','205142','205145','205147','205151','205152','205302','206301','206302','206303','206451','207126','207501','207502','207503','207504','207505','208028','208029','209201','209344','209407','209451','209506','209746','210010','211009','212403','212623','212660','212662','212666','215126','216221','221111','221113','221209','221210','221714','221719','221721','221722','222005','222101','222102','222103','222104','222107','222108','222110','222112','222113','223106','223107','224166','224184','224211','225402','225406','225407','225408','225411','227101','227105','227107','227111','227115','227116','227120','227125','227131','227132','227202','227205','227207','227301','227302','227305','227308','227309','228411','229415','229416','229417','229418','229419','229502','229503','229504','229508','229841','229881','230104','230122','230123','230140','230145','230146','230305','230406','231310','232114','232115','232116','232119','232221','232338','233235','233236','241501','241502','241503','241504','243215','243621','243640','245401','245402','245403','245405','245407','245408','245409','245411','245412','246451','246452','246454','246456','246458','246476','246489','246738','246768','247769','248004','248010','248110','248115','248126','248141','248148','248152','248160','248161','248167','249142','249147','250251','262519','262571','262574','263002','263129','263155','263654','263662','263675','263677','263683','263684','263686','263687','271127','271128','271211','271214','271315','271316','271317','271318','271320','271404','271406','271606','271608','271823','272003','272132','272149','272196','273307','274249','275207','275208','277122','277212','277218','277305','277306','277307','277405','285134','285196','285211','285231','301031','301033','301034','301042','301700','302007','302008','302009','302010','302011','302014','302023','302024','302025','302032','302205','302902','303115','303310','303314','303324','303331','303339','303340','303610','303802','305008','305416','306027','306106','311012','311013','311028','311607','312621','313015','321417','326510','331033','335806','341525','342004','342010','342320','360300','361141','362004','363002','364465','364470','364490','364526','365632','365641','365660','370002','370411','370429','370635','370640','380010','380012','380017','380025','380053','382001','382002','382004','382005','382009','382011','382012','382013','382015','382017','382019','382020','382022','382023','382025','382026','382027','382029','382043','382044','382051','382325','382346','382352','382410','382710','382711','382730','382732','382745','382750','382755','382760','382765','382780','382815','382820','382825','382830','382840','382850','382860','382861','382865','382870','382875','384205','384273','387250','387331','387421','387534','388275','390005','390008','391346','391460','391535','392031','392161','392162','394220','394251','395345','395620','396175','400040','400044','400045','400046','400047','400048','400062','400100','400613','401104','401609','401610','403003','403407','403603','403604','411010','411029','412114','412407','413225','413233','413235','413245','413580','415118','415120','415210','415416','415417','415418','415630','415704','416117','416127','416129','416130','416134','416217','416222','416224','416228','416317','416319','416320','416321','416421','416422','416423','416425','416426','416428','416536','416538','416541','416622','421001','421003','421206','421504','424116','424209','425106','425120','425121','425135','425312','425318','425319','425321','425323','425326','425509','425510','425511','425512','425515','425516','425517','425518','425519','425520','425522','425523','440004','440009','440028','441504','441918','441920','442005','442103','444700','444718','444728','444811','444812','444814','444815','444819','444827','444911','444913','444921','450343','450992','452004','452008','454020','454129','454749','460660','460669','462007','462013','462021','462032','470122','482007','483050','490012','490027','490028','491002','491003','491004','491050','491113','492006','492007','492033','492102','492104','493211','495634','495667','495678','495679','495680','497210','500264','530006','530010','530019','530035','530037','530042','533008','534229','560014','560019','560028','560031','560039','560044','560052','560069','560106','560242','561229','562124','562137','562140','562158','571149','571174','571437','571491','571501','571502','571810','572143','572144','573114','573149','573150','574128','574138','574139','574169','574258','574264','574301','574504','575328','576126','576127','576244','576254','577119','577142','581305','584112','584114','584119','584121','584130','584131','584166','586126','600029','600079','600105','600108','600111','600112','606112','606120','607110','612107','612108','612206','614209','614627','614632','621015','621016','621018','621022','621121','621126','621132','621201','621221','621303','621304','622406','622408','622419','623539','623544','623719','623801','623802','623804','623807','624213','624228','624314','624316','624624','624714','624803','625013','625209','625217','625538','625552','627051','627121','627129','627131','627361','627431','627435','627436','627551','627658','627659','627724','627763','627765','627770','627773','627801','627810','627817','627821','627867','627954','629181','629183','629187','629188','629189','629190','629191','629194','629195','629197','629253','629806','629807','629808','629854','630004','630006','630214','630310','630318','630505','630565','632402','636407','636802','638058','638466','638512','641061','641063','641106','642118','642124','642131','642153','670144','670330','670332','670333','670337','670339','670343','670346','670354','670522','670564','670732','671328','671329','671341','671349','671353','671357','673013','673023','673024','673025','673026','673107','673108','673109','673110','673111','673318','673321','673325','673326','673327','673510','673512','673515','673516','673518','673519','673520','673530','673532','673534','673544','673583','673615','673617','673618','673619','673621','673623','673624','673643','673644','673648','673649','673651','673652','673653','676110','676111','676126','676127','676308','676310','676313','676315','676318','676511','676513','676514','676515','676516','676554','676556','678015','678017','678018','678019','678020','678547','678548','678558','678559','678575','678589','678600','678605','678609','678614','678615','678616','678634','678635','678637','678689','678707','678709','678733','678752','679124','679125','679310','679311','679312','679314','679342','679343','679344','679348','679350','679351','679354','679355','679517','679518','679537','679538','679588','679589','679592','679594','680015','680016','680017','680018','680124','680313','680314','680316','680319','680321','680322','680323','680325','680547','680549','680554','680573','680574','680575','680592','680593','680595','680597','680600','680603','680608','680610','680621','680657','680672','680673','680693','680695','680735','680752','680771','682014','682043','682319','682320','682510','683107','683109','683524','683553','683554','683557','683564','683582','683583','683584','683586','683593','685502','685506','685510','685536','685537','685538','685539','685556','685564','685569','685592','685611','685621','686107','686124','686142','686145','686523','686549','686552','686588','686589','686591','686592','686594','686596','686597','686600','686614','686617','686620','686638','686640','686641','686642','686674','686676','686677','686679','686686','686687','686689','686695','686698','686721','686723','686726','686730','688508','689114','689125','689517','689518','689575','689576','689577','689578','689579','689596','689598','689600','689603','689616','689629','689630','689632','689657','689659','689660','689665','689680','689682','689703','689706','689722','690109','690541','690543','690557','690568','690569','690570','691017','691018','691315','691316','691318','691320','691321','691324','691326','691329','691513','691514','691517','691518','691519','691528','691539','691542','691544','691545','691546','691547','691548','691550','691562','691580','691587','691604','691623','691625','695031','695039','695041','695120','695127','695130','695131','695314','695315','695509','695510','695544','695560','695618','711224','711311','711321','711323','711324','711325','711326','711327','711328','711402','711406','711415','711416','712150','712153','712154','712156','712157','712158','712205','712247','712307','712309','712411','712418','712419','712420','712422','712423','712424','712426','712428','712429','712703','712704','712705','712707','712708','713402','722107','722159','722168','722175','722176','722180','731203','731251','731252','732143','732211','732212','733131','733144','733146','733147','733149','733151','733153','733154','733155','733211','733213','733214','733216','733246','733252','734121','734122','734123','734124','734227','734317','734319','734320','734321','734405','734431','734502','741104','741168','741169','741170','741171','741172','741173','741174','741175','741176','741177','741179','741183','741184','741185','741186','741187','741188','741189','741190','741191','741192','741196','741199','741203','741224','741225','741236','741258','741318','741403','741510','741511','741514','741516','742000','742150','742169','742170','742171','742173','742185','742188','742286','742307','743101','743150','743155','743170','743175','743176','743177','743178','743186','743195','743201','743244','743246','743250','743269','743274','743276','743288','743295','743298','743299','743301','743304','743339','743343','743352','743381','743384','743385','743389','743390','743391','743392','743396','743398','743413','743414','743440','743441','743443','743486','743506','743507','743508','743510','743601','743603','743606','743700','743703','743706','743708','743744','744019','744108','744110','744111','753005','753051','754081','754118','754226','754238','754241','754247','754261','754285','754286','754288','755021','755029','755032','755035','755038','756142','768026','781112','781130','784162','784181','784183','784185','785005','785604','785617','787160','788008','788122','788721','790010','795015','799055','800111','801101','801118','801501','801502','802173','802182','803206','813112','813113','813115','813117','813119','813121','813129','814122','825173','826124','827011','828102','829120','829145','831010','831018','832110','835240','843132','843141','843146','843153','843161','851122']

for pincode in pincodes:
    # URL of the webpage containing the table
    url = f'https://indiamapia.com/{pincode}.html'

    # Read the HTML content and extract tables using Pandas
    tables = pd.read_html(url)
    try:
        type1.append(tables[1][1][1])
        type2.append(tables[0][1][0])
        type1_pincodes.append(tables[1][0][1])
        type2_pincodes.append(tables[0][1][1])

    except:
        print(pincode)

124405
160061
160106
184146
208028
208029
209451
212403
222005
222104
224184
224211
227120
227205
229508
230104
248004
250251
271823
301031
301033
301034
301042
301700
302007
302008
302009
302010
302014
302205
302902
303115
303310
303314
303324
303340
303610
305416
321417
335806
341525
342320
360300
364526
365641
380010
380012
380017
380025
380053
382001
382002
382004
382005
382009
382011
382012
382013
382015
382017
382019
382020
382022
382023
382025
382026
382027
382029
382043
382044
382325
382346
382352
382410
387421
387534
390005
394251
400040
400044
400045
400046
400047
400048
400062
400100
400613
403003
411010
411029
412407
421003
421206
425312
425319
425321
425323
425512
425515
425516
425517
425518
425520
425522
444700
450343
450992
452004
490012
490027
490028
491002
491003
491004
491050
491113
492033
492102
492104
495634
495667
495679
495680
497210
500264
530006
530010
530019
530037
530042
560031
560044
560242
561229
562124
562137
562140
562158
571149
571174
573149
574128
575328
600029
600079
600105
600111
625013
641061
641063
676516
682014
682043
689600
691562
695041
711224
711311
711321
711323
711402
711406
712153
712205
712307
712703
722159
731252
733146
734405
741104
741174
741175
741176
741177
741179
741186
741190
741199
741236
742169
743101
743150
743155
743170
743175
743176
743177
743178
743186
743195
743201
743246
743250
743298
743301
743343
743381
743506
743508
743510
744019
754247
790010
802173
802182
813121
825173

In [23]:
pincode_localities = pd.DataFrame({'type1_pincodes':type1_pincodes, 'type1': type1, 'type2_pincodes':type2_pincodes, 'type2': type2})
pincode_localities

     type1_pincodes                  type1 type2_pincodes   type2
0            121011  Gurukul Indraprashtha            NaN     NaN
1            124524                  Chiri            NaN     NaN
2            127020           Bseh Bhiwani            NaN     NaN
3            127110                 Ranila            NaN     NaN
4            131002               Bhatgaon            NaN     NaN
...             ...                    ...            ...     ...
1032         843141                Jasauli            NaN     NaN
1033            NaN                    NaN         843146  Khabra
1034         843153               Morsandi            NaN     NaN
1035         843161                 Singar            NaN     NaN
1036         851122                Tilrath            NaN     NaN

[1037 rows x 4 columns]

In [52]:
df.to_csv('india_mapia_pin_names.csv', index=False)